"""empty message

Revision ID: fb933c09f1dc
Revises: c1851d3e9782
Create Date: 2024-05-22 16:03:08.928342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb933c09f1dc'
down_revision = 'c1851d3e9782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
